FROM ubuntu:16.04

RUN apt update && apt upgrade -y
RUN apt install -y git php libapache2-mod-php simplesamlphp php-mysql
RUN apt install -y vim

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

CMD /usr/sbin/apache2 -D FOREGROUND